# Generated by Django 4.1.5 on 2023-02-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_admin_owner_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rent', models.CharField(max_length=20)),
                ('rules', models.TextField()),
                ('amenities', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.ownerprofile')),
            ],
            options={
                'verbose_name_plural': 'dormitories',
            },
        ),
    ]
